# Generated by Django 3.2.19 on 2023-05-22 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='buildings'),
        ),
        migrations.AddField(
            model_name='department',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='departments'),
        ),
        migrations.AddField(
            model_name='desk',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='desks'),
        ),
        migrations.AddField(
            model_name='room',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='rooms'),
        ),
    ]
