# Generated by Django 3.2.19 on 2023-05-24 08:42

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_auto_20230522_1602'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to='images')),
                ('shape', models.CharField(blank=True, default='rect', max_length=20, null=True)),
                ('coords', models.CharField(blank=True, default='0,0,0,0', max_length=40, null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')])),
            ],
        ),
        migrations.RemoveField(
            model_name='building',
            name='image',
        ),
        migrations.RemoveField(
            model_name='department',
            name='image',
        ),
        migrations.RemoveField(
            model_name='desk',
            name='image',
        ),
        migrations.RemoveField(
            model_name='room',
            name='image',
        ),
        migrations.AddField(
            model_name='building',
            name='image_map',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.imagemap'),
        ),
        migrations.AddField(
            model_name='department',
            name='image_map',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.imagemap'),
        ),
        migrations.AddField(
            model_name='desk',
            name='image_map',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.imagemap'),
        ),
        migrations.AddField(
            model_name='room',
            name='image_map',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.imagemap'),
        ),
    ]
