# Generated by Django 3.2.19 on 2023-05-24 09:08

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_auto_20230524_1042'),
    ]

    operations = [
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shape', models.CharField(blank=True, default='rect', max_length=20, null=True)),
                ('coords', models.CharField(blank=True, default='0,0,0,0', max_length=40, null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')])),
            ],
        ),
        migrations.RemoveField(
            model_name='building',
            name='image_map',
        ),
        migrations.RemoveField(
            model_name='department',
            name='image_map',
        ),
        migrations.RemoveField(
            model_name='desk',
            name='image_map',
        ),
        migrations.RemoveField(
            model_name='room',
            name='image_map',
        ),
        migrations.AddField(
            model_name='building',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='buildings'),
        ),
        migrations.AddField(
            model_name='department',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='departments'),
        ),
        migrations.AddField(
            model_name='room',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='rooms'),
        ),
        migrations.DeleteModel(
            name='ImageMap',
        ),
        migrations.AddField(
            model_name='department',
            name='map',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.map'),
        ),
        migrations.AddField(
            model_name='desk',
            name='map',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.map'),
        ),
        migrations.AddField(
            model_name='room',
            name='map',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.map'),
        ),
    ]
