# Generated by Django 3.2.19 on 2023-05-24 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_auto_20230524_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='name',
            field=models.CharField(default='DEF', max_length=30, unique=True),
            preserve_default=False,
        ),
    ]
