# Generated by Django 3.2.19 on 2023-05-26 12:48

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_map_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='map',
            name='shape',
        ),
        migrations.AlterField(
            model_name='map',
            name='coords',
            field=models.CharField(blank=True, default='0,0, 0,0, 0,0, 0,0', max_length=100, null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')]),
        ),
    ]
