# Generated by Django 3.2.19 on 2023-06-01 08:32

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_auto_20230526_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='map',
            name='coords',
            field=models.CharField(blank=True, default='0,0, 0,0, 0,0, 0,0', max_length=1000, null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')]),
        ),
    ]
