# Generated by Django 3.2.19 on 2023-06-01 09:30

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_alter_map_coords'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='map',
        ),
        migrations.RemoveField(
            model_name='desk',
            name='map',
        ),
        migrations.RemoveField(
            model_name='room',
            name='map',
        ),
        migrations.AddField(
            model_name='department',
            name='coords',
            field=models.CharField(blank=True, default='', max_length=1000, null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')]),
        ),
        migrations.AddField(
            model_name='desk',
            name='coords',
            field=models.CharField(blank=True, default='', max_length=1000, null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')]),
        ),
        migrations.AddField(
            model_name='room',
            name='coords',
            field=models.CharField(blank=True, default='', max_length=1000, null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')]),
        ),
    ]
