# Generated by Django 3.2.19 on 2023-06-01 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_auto_20230601_1130'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Map',
        ),
    ]
