# Generated by Django 3.2.19 on 2023-06-01 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_delete_map'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='address',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='building',
            name='name',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
